In this exercise you'll try to build a neural network that predicts the price of a house according to a simple formula.

So, imagine if house pricing was as easy as a house costs 50k + 50k per bedroom, so that a 1 bedroom house costs 100k, a 2 bedroom house costs 150k etc.

How would you create a neural network that learns this relationship so that it would predict a 7 bedroom house as costing close to 400k etc.

Hint: Your network might work better if you scale the house price down. You don't have to give the answer 400...it might be better to create something that predicts the number 4, and then your answer is in the 'hundreds of thousands' etc.

In [2]:
import tensorflow as tf
import numpy as np
from tensorflow import keras

In [8]:
print(np.linspace(1, 5, 5))
print(np.arange(1.0, 5.0+1.0))

[1. 2. 3. 4. 5.]
[1. 2. 3. 4. 5.]


In [12]:
np.arange(1, 5.5 + 0.5, 0.5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5])

In [13]:
# GRADED FUNCTION: house_model
def house_model(y_new):
    xs = np.arange(1.0, 10.0 + 1.0) # number of bedrooms
    ys = np.arange(1, 5.5 + 0.5, 0.5)
    model = tf.keras.Sequential([keras.layers.Dense(1, input_shape=[1])])
    model.compile(optimizer='sgd', loss='mse')
    model.fit(xs, ys, epochs=100)
    return model.predict(y_new)[0]

In [14]:
prediction = house_model([7.0])
print(prediction)

W1229 20:59:01.659445 140506442368832 deprecation.py:506] From /usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/init_ops.py:1251: calling VarianceScaling.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor


Epoch 1/100
10/10 [==============================] - 2s 219ms/sample - loss: 7.2042
Epoch 2/100
10/10 [==============================] - 0s 152us/sample - loss: 0.3942
Epoch 3/100
10/10 [==============================] - 0s 134us/sample - loss: 0.0813
Epoch 4/100
10/10 [==============================] - 0s 119us/sample - loss: 0.0664
Epoch 5/100
10/10 [==============================] - 0s 124us/sample - loss: 0.0652
Epoch 6/100
10/10 [==============================] - 0s 107us/sample - loss: 0.0646
Epoch 7/100
10/10 [==============================] - 0s 120us/sample - loss: 0.0640
Epoch 8/100
10/10 [==============================] - 0s 134us/sample - loss: 0.0635
Epoch 9/100
10/10 [==============================] - 0s 135us/sample - loss: 0.0630
Epoch 10/100
10/10 [==============================] - 0s 139us/sample - loss: 0.0624
Epoch 11/100
10/10 [==============================] - 0s 114us/sample - loss: 0.0619
Epoch 12/100
10/10 [==============================] - 0s 136us/sample - lo

In [4]:
# Now click the 'Submit Assignment' button above.
# Once that is complete, please run the following two cells to save your work and close the notebook

In [15]:
%%javascript
<!-- Save the notebook -->
IPython.notebook.save_checkpoint();

<IPython.core.display.Javascript object>

In [ ]:
%%javascript
IPython.notebook.session.delete();
window.onbeforeunload = null
setTimeout(function() { window.close(); }, 1000);

<IPython.core.display.Javascript object>